CommunitySeedConsulting/config/routes.rb
Rails.application.routes.draw do

  get 'contact_us/index'

  get 'volunteers/index'

  get 'community_partner/index'

  get 'about_us/index'

  get "home" => "home#index"

  

end

CommunitySeedConsulting/app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
  def index
  end
end

CommunitySeedConsulting/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

CommunitySeedConsulting/app/controllers/community_partner_controller.rb
class CommunityPartnerController < ApplicationController
  def index
  end
end

CommunitySeedConsulting/app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController
  def index
  end
end

CommunitySeedConsulting/app/controllers/home_controller.rb
class HomeController < ApplicationController
end

CommunitySeedConsulting/app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  def index
  end
end

CommunitySeedConsulting/app/helpers/about_us_helper.rb
module AboutUsHelper
end

CommunitySeedConsulting/app/helpers/application_helper.rb
module ApplicationHelper

	  def active?(controller)
    if params[:controller] == controller
      "active"
    end
  end

end

CommunitySeedConsulting/app/helpers/community_partner_helper.rb
module CommunityPartnerHelper
end

CommunitySeedConsulting/app/helpers/contact_us_helper.rb
module ContactUsHelper
end

CommunitySeedConsulting/app/helpers/home_helper.rb
module HomeHelper
end

CommunitySeedConsulting/app/helpers/volunteers_helper.rb
module VolunteersHelper
end

CommunitySeedConsulting/app/views/community_partner/index.html.erb
<section class="banner">

  <div class="container">   
   <div class="col-md-12 text-center">
      <h2>We bring fresh ideas and perspectives to non-profits.</h2>
    </div>
  </div>

</section>



<section class="contact-2 light-gray-bg">
    <div class="container">
        <div data-scroll-reveal class="row">
            <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1 text-center">
                <h4>Community Partner Form</h4>
                <br/>
                <form class="contact-form" role="form" action="post">
                    <input name="name" id="name" class="form-control" type="text" placeholder="Name">
                    <input name="position" id="position" class="form-control" type="text" placeholder="Position">
                    <input name="mail" id="mail" class="form-control" type="text" placeholder="E-mail">
                    <input name="company" id="company" class="form-control" type="text" placeholder="Company">
                    <textarea name="comment" id="comment" class="form-control" rows="5" placeholder="Message"></textarea>
                    <button type="submit" name="contact-submit" id="submit_contact" class="btn btn-primary btn-block">Submit</button>
                </form>
<!--                 <ul class="social">
                    <li><a href="#"><i class="fa fa-twitter fa-lg"></i></a></li>
                    <li><a href="#"><i class="fa fa-facebook fa-lg"></i></a></li>
                    <li><a href="#"><i class="fa fa-dribbble fa-lg"></i></a></li>
                </ul> -->
            </div>
        </div>
    </div>
</section>

CommunitySeedConsulting/app/views/contact_us/index.html.erb
<section class="contact-1">
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div data-scroll-reveal class="row">
                    <div class="col-md-12 text-center">
                        <h2>Get In Touch</h2>
                        <img src="https://s3.amazonaws.com/communityseed/commseedlogoleaf.gif" alt="placehold.it" height="50px" class="placehold">
                    </div>
                </div>
                <div class="row">
                    <div data-scroll-reveal="enter from the left" class="col-md-7">
                        <form class="contact-form" role="form" action="post">
                            <input name="name" id="name" class="form-control" type="text" placeholder="Name">
                            <input name="mail" id="mail" class="form-control" type="text" placeholder="Your e-mail">
                            <input name="website" id="website" class="form-control" type="text" placeholder="Website">
                            <textarea name="comment" id="comment" class="form-control" rows="5" placeholder="Message"></textarea>
                            <button type="submit" name="contact-submit" id="submit_contact" class="btn btn-primary btn-block">Submit</button>
                        </form>
                    </div>
                    <div class="col-md-5">
                        <div data-scroll-reveal="wait .25s, enter from the top"  class="contact-info">
                            <!-- Start Contact Details  -->
                            <ul class="contact-list">
                                <li><i class="fa fa-envelope-o"></i><a href="mailto:info@communityseedconsulting.com">info@communityseedconsulting.com</a></li>
                            </ul>
                            <!-- End Contact Details  -->
                        </div>
<!--                         <hr data-scroll-reveal="wait .25s, enter from the top" >
                        <div data-scroll-reveal="wait .5s, enter from the bottom" class="social">
                            <h5>Find us online</h5>
                            <!-- Start  Social Links -->
<!--                             <ul class="social">
                                <li class="facebook"> <a href="#"> <i class="fa fa-facebook"></i> </a> </li>
                                <li class="twitter"> <a href="#"> <i class="fa fa-twitter"></i> </a> </li>
                                <li class="google-plus"> <a href="#"> <i class="fa fa-google-plus"></i> </a> </li>
                                <li class="linkedin"> <a href="#"> <i class="fa fa-linkedin"></i> </a> </li>
                                <li class="youtube"> <a href="#"> <i class="fa fa-youtube-play"></i> </a> </li>
                            </ul> -->
                            <!-- End Social Links  -->
                        </div> 
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

CommunitySeedConsulting/app/views/home/index.html.erb
<!-- from http://bootsnipp.com/snippets/featured/responsive-quote-carousel -->
<script src="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.2.0/js/carousel.min.js"></script>

<script type="text/javascript">
  // When the DOM is ready, run this function
$(document).ready(function() {
  //Set the carousel options
  $('#quote-carousel').carousel({
    pause: true,
    interval: 4000,
  });
});
</script>


<div class="welcome-2">
	<div class="container center-vertically">
    <div class="row">
      <div class="transparent-background col-md-offset-3 col-md-6">
    		<h1 data-scroll-reveal>Growing Community Impact.</h1>
        <h4 data-scroll-reveal>Community Seed organizes professionals to give their time and skills to grow non-profits success</h4>
      </div>
    </div>
    <br>
		<div data-scroll-reveal="wait .5s">
      <h5>Scroll down to learn more about us</h5><br>
      <div class="fa fa-2x fa-angle-double-down"></div>
    </div>
	</div>
</div>

<!-- ABOUT US -->

<section class="services-1 container">
  
    <div data-scroll-reveal class="row services-1-groupings">
      <div class="col-md-4">
        <h2>Experienced volunteers</h2>
      </div>
      <div class="col-md-8">
        <p>Highly-skilled volunteer professionals who provide pro-bono consulting and professional services to non-profits ranging from marketing strategy to operational optimization</p>
      </div>
    </div>

    <div data-scroll-reveal class="row services-1-groupings">
      <div class="col-md-4">
        <h2>Partnering with the non-profit sector</h2>
      </div>
      <div class="col-md-8">
        <p>Community Seed facilitates grassroots growth of local non-profits – our Community Partners— by offering consultative services and providing better value to volunteers, donors, and communities who support a charitable cause.</p>
      </div>
    </div>

    <div data-scroll-reveal class="row services-1-groupings">
      <div class="col-md-4">
        <h2>Delivering realistic & sustainable solutions</h2>
      </div>
      <div class="col-md-8">
        <p>Our goal is to ensure Community Partners leave with the training and resources they need to implement positive change and continue to focus on improvements toward the achievement of their mission(s). We also leave them with a plan on how to track these improvements, and we check-up on clients and provide periodic review to enable steady growth</p>
      </div>
    </div>

</section>

<!--SERVICES -->

<section class="services-2">
  <div class="light-gray-bg">

    <%= render 'shared/services' %>
  </div>
</section>






<!--TESTIMONIALS -->
<section>

	<div class="container">
    <div class="carousel slide" data-ride="carousel" id="quote-carousel">
      <!-- Bottom Carousel Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#quote-carousel" data-slide-to="0" class="active"></li>
        <li data-target="#quote-carousel" data-slide-to="1"></li>
        <li data-target="#quote-carousel" data-slide-to="2"></li>
      </ol>
      
      <!-- Carousel Slides / Quotes -->
      <div class="carousel-inner">
      
        <!-- Quote 1 -->
        <div class="item active">
          <blockquote>
            <div class="row">
              <div class="col-sm-3 text-center">
                <img class="img-circle" src="https://s3.amazonaws.com/communityseed/Alzheimer+Society+Logo.jpg" style="width: 100px;height:100px;">
              </div>
              <div class="col-sm-9">
                <h2>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut rutrum elit in arcu blandit.</h2>
                <small>Alzheimer Society Toronto</small>
              </div>
            </div>
          </blockquote>
        </div>
        <!-- Quote 2 -->
        <div class="item">
          <blockquote>
            <div class="row">
              <div class="col-sm-3 text-center">
                <img src="https://s3.amazonaws.com/communityseed/World+Partnership+Walk+logo.jpg" style="width: 200px;">
              </div>
              <div class="col-sm-9">
                <h2>Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit!</h2>
                <small>World Parntnership Walk</small>
              </div>
            </div>
          </blockquote>
        </div>
        <!-- Quote 3 -->
        <div class="item">
          <blockquote>
            <div class="row">
             <div class="col-sm-3 text-center">
                <img  src="https://s3.amazonaws.com/communityseed/Youth+Challenge+International+Logo.jpg" style="width: 200px;">
              </div>
              <div class="col-sm-9">
                <h2>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam auctor nec lacus ut tempor. Mauris.</h2>
                <small>Youth Challenger International</small>
              </div>
            </div>
          </blockquote>
        </div>
      </div>
      
      <!-- Carousel Buttons Next/Prev -->
      <a data-slide="prev" href="#quote-carousel" class="left carousel-control"><i class="fa fa-chevron-left"></i></a>
      <a data-slide="next" href="#quote-carousel" class="right carousel-control"><i class="fa fa-chevron-right"></i></a>
    </div>                          
  </div>
</section>
	
	<!--CALL TO ACTION -->
<section class="call-to-action">
  <div class="light-gray-bg text-center">
  	<div class="container">
  		<div data-scroll-reveal class="row">
  			<div class="row">
  				<div class="col-lg-6">
  					<p>Interested in volunteering with us?</p>
  				</div>
  				<div class="col-lg-6">
  					<p>Interested in partnerning with us?</p>
  				</div>
  			</div>
  			<div class="row">
  				<div class="col-lg-2 col-lg-offset-2">
            <%= link_to volunteers_index_path do %>
  						<div class="btn btn-green btn-lg btn-block">Start now</div>
            <% end %>
  				</div>
  				<div class="col-lg-2 col-lg-offset-4">
            <%= link_to community_partner_index_path do %>
              <div class="btn btn-green btn-lg btn-block">Let's Talk</div>
            <% end %>
  				</div>
  			</div>
  		</div>
  	</div>
  </div>
</section>



<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/scrollReveal.js/0.1.2/scrollReveal.min.js"></script>
<script>
// The starting defaults.
var config = {
		after: '0s',
		enter: 'bottom',
		move: '24px',
		over: '0.66s',
		easing: 'ease-in-out',
		viewportFactor: 0.33,
		reset: false,
		init: true
	  };

window.scrollReveal = new scrollReveal( config );
</script>

CommunitySeedConsulting/app/views/layouts/_footer.html.erb
<!--FOOTER -->

<footer class="footer-4">
    <div class="container text-center">
        <p>Community Seed Consulting</p>
    </div>
</footer>

CommunitySeedConsulting/app/views/layouts/_navbar.html.erb
<nav id="navigation" class="navbar navbar-default navbar-fixed-top navbar-2" role="navigation">
    <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header nav-logo">
            <%= link_to home_path do %><%= image_tag("logo_no_bg.gif", height: '30')%><% end %> 
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to about_us_index_path, :class => active?('about_us') do %>Who We Are<% end %></li>
                <li><%= link_to community_partner_index_path, :class => active?('community_partner') do %>Community Partners<% end %></li>
                <li><%= link_to volunteers_index_path, :class => active?('volunteers') do %>Volunteer<% end %></li>
                <li><a href="#supporters">Supporters</a></li>
                <li><%= link_to contact_us_index_path, :class => active?('contact_us') do %>Contact Us<% end %></li>
            </ul>

        </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
</nav>

CommunitySeedConsulting/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CommunitySeedConsulting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- ADD -->
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>


<!-- only not show nav bar when first visit home page-->
<% if controller.controller_name == 'home' %>
	<header class="no-display">
<% end %>

<%= render 'layouts/navbar' %> 

<% if controller.controller_name == 'home' %>
	</header>
<% end %>

<%= yield %>

<%= render 'layouts/footer' %> 

</body>
</html>

CommunitySeedConsulting/app/views/shared/_services.html.erb
<!-- SERVICES -->


        <div class="container">
            <div data-scroll-reveal="enter from the left" class="row">
                  <div class="col-md-5">
                      <h2>Our Services</h2>
                  </div>
            </div>
        </div>
      <div data-scroll-reveal class="container">
          <div class="row">
                <div class="col-md-6">
                    <div class="row service-item">
                        <div class="col-md-3 service-icon">
                            <span class="fa fa-3x fa-sitemap"></span>
                        </div>
                        <div class="col-md-9">
                            <h5>Organizational Development</h5>
                        </div>
                    </div>
                    <div class="row service-item">
                        <div class="col-md-3 service-icon">
                           <span class="fa fa-3x fa-line-chart"></span>
                        </div>
                        <div class="col-md-9">
                            <h5>Strategic Planning</h5>
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="row service-item">
                        <div class="col-md-3 service-icon">
                            <span class="fa fa-3x fa-dashboard"></span>
                        </div>
                        <div class="col-md-9">
                            <h5>Performance Measurement</h5>
                        </div>
                    </div>
                    <div class="row service-item">
                        <div class="col-md-3 service-icon">
                            <span class="fa fa-3x fa-users"></span>
                        </div>
                        <div class="col-md-9">
                            <h5>Human Capital</h5>
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="row service-item">
                        <div class="col-md-3 service-icon">
                            <span class="fa fa-3x fa-dollar"></span>
                        </div>
                        <div class="col-md-9">
                            <h5>Funding and Marketing Strategy</h5>
                        </div>
                    </div>
                    <div class="row service-item">
                        <div class="col-md-3 service-icon">
                            <span class="fa fa-3x fa-file-text"></span>
                        </div>
                        <div class="col-md-9">
                            <h5>Market Studies and Research</h5>
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="row service-item">
                        <div class="col-md-3 service-icon">
                            <span class="fa fa-3x fa-star"></span>
                        </div>
                        <div class="col-md-9">
                            <h5>New Services Development</h5>
                        </div>
                    </div>
                </div>

          </div>
        </div>
    </div>
</section>

CommunitySeedConsulting/app/views/volunteers/index.html.erb
<section class="banner">

  <div class="container">   
   <div class="col-md-12 text-center">
      <h2>Join a network of diverse professionals that achieve meaningful change.</h2>
    </div>
  </div>

</section>



<section class="contact-2 light-gray-bg">
    <div class="container">
        <div data-scroll-reveal class="row">
            <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1 text-center">
                <h4>Volunteer Form</h4>
                <br/>
                <form class="contact-form" role="form" action="post">
                    <input name="name" id="name" class="form-control" type="text" placeholder="Name">
                    <input name="mail" id="mail" class="form-control" type="text" placeholder="E-mail">
                    <div class="form-group">
                      <label for="inputProfession" class="col-sm-2 control-label">I am...</label>
                      <div class="col-sm-10">
                          <select class="form-control">
                            <option>a student</option>
                            <option>a working professional</option>
                            <option>other</option>
                          </select>
                      </div>
                    </div>
                    <br/><br/><br/>
                    <div class="form-group">
                      <button type="submit" name="contact-submit" id="submit_contact" class="btn btn-primary btn-block">Submit</button>
                    </div>
                </form>
<!--                 <ul class="social">
                    <li><a href="#"><i class="fa fa-twitter fa-lg"></i></a></li>
                    <li><a href="#"><i class="fa fa-facebook fa-lg"></i></a></li>
                    <li><a href="#"><i class="fa fa-dribbble fa-lg"></i></a></li>
                </ul> -->
            </div>
        </div>
    </div>
</section>